AWSTemplateFormatVersion: '2010-09-09-OC'

Parameters:

  instanceArn:
    Type: String

  principalId:
    Type: String

  permissionSetName:
    Type: String
    Default: Security

  sessionDuration:
    Type: String
    Default: PT1H

OrganizationBindings:

  RoleBinding:
    OrganizationalUnit: !Ref ProdOU
    Region: 'eu-west-2'

Resources:

  SecurityPermissionSet:
    Type: AWS::SSO::PermissionSet
    Properties:
      Name: !Ref permissionSetName
      Description: !Sub '${permissionSetName} access to AWS organization'
      InstanceArn: !Ref instanceArn
      ManagedPolicies: 
      - arn:aws:iam::aws:policy/AdministratorAccess
      SessionDuration: !Ref sessionDuration
      InlinePolicy:
        Version: 2012-10-17
        Statement:
          - Sid: 'DenyAccessToElevatedRole'
            Effect: Deny
            Action: sts:AssumeRole
            Resource: Fn::EnumTargetAccounts RoleBinding 'arn:aws:iam::${account}:role/elevated-security-role'

  SecurityLogArchiveAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref instanceArn
      PermissionSetArn: !GetAtt SecurityPermissionSet.PermissionSetArn
      PrincipalId: !Ref principalId
      PrincipalType: GROUP
      TargetType: AWS_ACCOUNT
      TargetId: !GetAtt LogArchiveAccount.AccountId

  SecurityToolingAssignment:
    Type: AWS::SSO::Assignment
    Properties:
      InstanceArn: !Ref instanceArn
      PermissionSetArn: !GetAtt SecurityPermissionSet.PermissionSetArn
      PrincipalId: !Ref principalId
      PrincipalType: GROUP
      TargetType: AWS_ACCOUNT
      TargetId: !GetAtt SecurityAccount.AccountId